import { cloneCase, type ECGCase } from "../engine/types";
import type { Preset } from "../presets/catalog";
export interface ExplorationOrigin { readonly presetId:string; readonly presetName:string; readonly case:ECGCase }
export interface ExplorationChange { readonly key:string; readonly label:string; readonly before:unknown; readonly after:unknown }
const LABELS:Record<string,string>={seed:"Semilla",rhythm:"Ritmo",ventricularSource:"Fuente ventricular",av:"Conducción AV",conduction:"Conducción intraventricular",ischemia:"Repolarización / lesión",overload:"Sobrecarga",hr:"Frecuencia ventricular",atrialRate:"Frecuencia auricular",variability:"Variabilidad RR",respiratoryRate:"Frecuencia respiratoria",pr:"PR",qrs:"QRS",qtc:"QTc programado",axis:"Eje QRS",pAxis:"Eje P",tAxis:"Eje T",pAmp:"Amplitud P",qrsAmp:"Amplitud QRS",tAmp:"Amplitud T",transition:"Transición precordial",septalQ:"Q septal",ectopy:"Ectopia",coupling:"Acoplamiento",flutterRatio:"Relación de conducción flutter",escape:"Escape",pacing:"Modo de marcapasos",st:"ST",phase:"Fase",stShape:"Morfología ST",electrolyte:"Modificador metabólico",filter:"Filtro",notch:"Notch",mainsFrequency:"Frecuencia de red","artifacts.baseline":"Deriva de línea de base","artifacts.muscle":"Artefacto muscular","artifacts.mains":"Interferencia de red","artifacts.loose":"Electrodo suelto","artifacts.reversed":"Inversión de brazos"};
const equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export function createExplorationOrigin(preset:Preset,c:ECGCase):ExplorationOrigin{return{presetId:preset.id,presetName:preset.name,case:cloneCase(c)}}
export function explorationChanges(origin:ExplorationOrigin,current:ECGCase):ExplorationChange[]{const out:ExplorationChange[]=[];for(const key of Object.keys(LABELS)){const [group,item]=key.split(".");const before=item?(origin.case[group as "artifacts"] as unknown as Record<string,unknown>)[item]:(origin.case as unknown as Record<string,unknown>)[key];const after=item?(current[group as "artifacts"] as unknown as Record<string,unknown>)[item]:(current as unknown as Record<string,unknown>)[key];if(!equal(before,after))out.push({key,label:LABELS[key],before,after})}return out}
export function restoreExplorationOrigin(origin:ExplorationOrigin,current:ECGCase):ECGCase{const restored=cloneCase(origin.case);restored.view=cloneCase(current).view;return restored}
export function sameExplorationModel(origin:ExplorationOrigin,current:ECGCase):boolean{return explorationChanges(origin,current).length===0}
