import { DEFAULT_CASE, cloneCase, type ECGCase } from "../engine/types";
export interface Preset {
  id: string;
  name: string;
  short: string;
  group: string;
  patch: Partial<ECGCase>;
  mechanism: string;
  findings: string[];
  strategy: "vectorial" | "local" | "pending";
  limitation: string;
}
const p = (
  id: string,
  name: string,
  short: string,
  group: string,
  patch: Partial<ECGCase>,
  mechanism: string,
  findings: string[],
  strategy: Preset["strategy"] = "vectorial",
  limitation = "Morfología paramétrica representativa; sin validación contra ECG de pacientes.",
): Preset => ({
  id,
  name,
  short,
  group,
  patch,
  mechanism,
  findings,
  strategy,
  limitation,
});
export const PRESETS: Preset[] = [
  p(
    "sinus",
    "Ritmo sinusal",
    "Sinusal",
    "Ritmos",
    {},
    "Activación auricular sinusal seguida de conducción AV 1:1.",
    [
      "P positiva en II, negativa en aVR",
      "PR constante; QRS estrecho",
      "Progresión de R precordial",
    ],
  ),
  p(
    "brady",
    "Bradicardia sinusal",
    "Bradicardia",
    "Ritmos",
    { hr: 45 },
    "Disminución de la frecuencia del nodo sinusal.",
    ["FC <60 lpm", "Una P antes de cada QRS"],
  ),
  p(
    "tachy",
    "Taquicardia sinusal",
    "Taquicardia",
    "Ritmos",
    { hr: 125, pr: 140, qtc: 410 },
    "Aumento de automatismo sinusal con conducción conservada.",
    ["FC >100 lpm", "P sinusal y relación AV 1:1"],
  ),
  p(
    "rsa",
    "Arritmia sinusal respiratoria",
    "Arritmia respiratoria",
    "Ritmos",
    { hr: 68, variability: 0.18 },
    "El intervalo PP se modula por la fase respiratoria.",
    ["Variación cíclica RR", "P de morfología constante"],
  ),
  p(
    "af",
    "Fibrilación auricular",
    "FA",
    "Ritmos",
    { rhythm: "af", hr: 95 },
    "Actividad auricular desorganizada y respuesta ventricular estocástica.",
    [
      "Ausencia de P organizadas",
      "RR irregularmente irregular",
      "Ondas f de baja amplitud",
    ],
  ),
  p(
    "af_fast",
    "FA con respuesta rápida",
    "FA rápida",
    "Ritmos",
    { rhythm: "af", hr: 145 },
    "Fibrilación auricular con respuesta ventricular rápida.",
    ["Irregularidad absoluta", "Frecuencia media elevada"],
  ),
  p(
    "af_slow",
    "FA con respuesta lenta",
    "FA lenta",
    "Ritmos",
    { rhythm: "af", hr: 48 },
    "Fibrilación auricular con conducción ventricular lenta.",
    ["Sin P organizadas", "RR largo e irregular"],
  ),
  p(
    "flutter",
    "Flutter auricular 2:1",
    "Flutter 2:1",
    "Ritmos",
    { rhythm: "flutter", atrialRate: 300, hr: 150, flutterRatio: 2 },
    "Actividad auricular periódica con conducción AV fija.",
    [
      "Ondas F negativas inferiores y positivas en V1",
      "Frecuencia auricular 300/min",
      "Respuesta ventricular 150 lpm",
    ],
    "vectorial",
    "Ondas F simplificadas; conducción variable y circuito de reentrada no modelados.",
  ),
  p(
    "flutter3",
    "Flutter auricular 3:1",
    "Flutter 3:1",
    "Ritmos",
    { rhythm: "flutter", atrialRate: 300, hr: 100, flutterRatio: 3 },
    "Conducción de una de cada tres activaciones auriculares.",
    ["Ondas F continuas", "Respuesta ventricular 100 lpm"],
  ),
  p(
    "svt",
    "Taquicardia supraventricular regular",
    "TSV",
    "Ritmos",
    { rhythm: "junctional", hr: 185, pr: 80 },
    "Aproximación de una taquicardia de origen supraventricular con activación retrógrada.",
    ["QRS estrecho y regular", "P retrógrada cercana al QRS"],
    "vectorial",
    "No distingue AVNRT de AVRT; pseudo-r′ y pseudo-S no ajustadas de forma específica.",
  ),
  p(
    "junctional",
    "Ritmo de la unión",
    "Unión",
    "Ritmos",
    { rhythm: "junctional", hr: 48 },
    "Ritmo de escape de la unión con activación auricular retrógrada.",
    ["QRS estrecho a 40–60 lpm", "P retrógrada negativa en II"],
  ),
  p(
    "pac",
    "Extrasístole auricular",
    "ESA",
    "Ectopia",
    { ectopy: "pac" },
    "Activación auricular prematura que reinicia el ciclo.",
    [
      "P precoz de morfología diferente",
      "QRS estrecho",
      "Pausa no compensadora",
    ],
  ),
  p(
    "pvc",
    "Extrasístole ventricular",
    "ESV",
    "Ectopia",
    { ectopy: "pvc" },
    "Activación ventricular prematura y pausa compensadora programada.",
    ["QRS ancho prematuro", "Repolarización secundaria", "Pausa compensadora"],
    "vectorial",
    "No modela penetración retrógrada ni disociación auricular durante la ectopia.",
  ),
  p(
    "bigeminy",
    "Bigeminismo ventricular",
    "Bigeminismo",
    "Ectopia",
    { ectopy: "bigeminy", hr: 70 },
    "Alternancia de complejos sinusales y ventriculares prematuros.",
    ["Un QRS sinusal y una ESV", "Acoplamiento fijo"],
  ),
  p(
    "trigeminy",
    "Trigeminismo ventricular",
    "Trigeminismo",
    "Ectopia",
    { ectopy: "trigeminy" },
    "Dos latidos sinusales seguidos por una extrasístole ventricular.",
    ["Secuencia de tres complejos", "ESV de morfología constante"],
  ),
  p(
    "couplet",
    "Dupla ventricular",
    "Dupla",
    "Ectopia",
    { ectopy: "couplet" },
    "Dos activaciones ventriculares prematuras consecutivas.",
    ["Dos QRS anchos consecutivos", "Pausa posterior"],
  ),
  p(
    "idioventricular",
    "Ritmo idioventricular",
    "Idioventricular",
    "Ritmos ventriculares",
    { rhythm: "idioventricular", hr: 32, qrs: 170, axis: -65 },
    "Escape ventricular lento.",
    ["QRS ancho", "Frecuencia 20–40 lpm"],
  ),
  p(
    "aivr",
    "Ritmo idioventricular acelerado",
    "RIVA",
    "Ritmos ventriculares",
    { rhythm: "idioventricular", hr: 78, qrs: 150, axis: -65 },
    "Automatismo ventricular acelerado.",
    ["QRS ancho regular", "Frecuencia aproximada 50–110 lpm"],
  ),
  p(
    "vt",
    "Taquicardia ventricular monomórfica",
    "TV monomórfica",
    "Ritmos ventriculares",
    { rhythm: "vt", hr: 170, atrialRate: 75, qrs: 165, axis: -65 },
    "Activación ventricular repetitiva con actividad auricular independiente.",
    ["QRS ancho regular", "Disociación AV", "Repolarización secundaria"],
    "vectorial",
    "Sin latidos de captura o fusión; una sola morfología representativa.",
  ),
  p(
    "torsades",
    "Taquicardia ventricular polimórfica",
    "TV polimórfica",
    "Ritmos ventriculares",
    { rhythm: "torsades", hr: 210, qrs: 160, qtc: 550 },
    "Rotación periódica del vector ventricular para representar torsión del eje.",
    ["Polaridad y amplitud variables", "Envolvente fusiforme"],
    "vectorial",
    "Aproximación visual. No reproduce QT previo ni inicio corto–largo–corto; no equivale a diagnóstico validado de torsades.",
  ),
  p(
    "vf",
    "Fibrilación ventricular",
    "FV",
    "Ritmos ventriculares",
    { rhythm: "vf" },
    "Actividad oscilatoria caótica sin complejos organizados.",
    ["Ausencia de QRS identificables", "Ondulación irregular continua"],
    "vectorial",
    "Suma oscilatoria sintética; transición gruesa a fina no modelada.",
  ),
  p(
    "asystole",
    "Asistolia",
    "Asistolia",
    "Ritmos ventriculares",
    { rhythm: "asystole" },
    "Ausencia de activación eléctrica organizada en el generador.",
    [
      "Línea isoeléctrica sin artefactos",
      "Comprobar otras derivaciones en la práctica",
    ],
  ),
  p(
    "av1",
    "BAV de primer grado",
    "BAV 1.º",
    "Conducción AV",
    { av: "first", pr: 260 },
    "Retardo AV constante sin pérdida de conducción.",
    ["PR >200 ms", "Todas las P conducidas"],
  ),
  p(
    "wenckebach",
    "BAV Mobitz I · Wenckebach",
    "Wenckebach",
    "Conducción AV",
    { av: "mobitz1", hr: 75, pr: 160, variability: 0 },
    "Incrementos PR de 80 y 40 ms seguidos de una P bloqueada; ciclo 4:3.",
    [
      "PR 160 → 240 → 280 ms",
      "Cuarta P bloqueada",
      "RR conducidos 880 → 840 ms",
    ],
  ),
  p(
    "mobitz2",
    "BAV de segundo grado Mobitz II",
    "Mobitz II",
    "Conducción AV",
    {
      av: "mobitz2",
      hr: 75,
      pr: 180,
      qrs: 140,
      conduction: "rbbb",
      variability: 0,
    },
    "Pérdida súbita de conducción con PR constante en los latidos conducidos.",
    ["PR constante", "Una P bloqueada por grupo", "QRS ancho representativo"],
  ),
  p(
    "av21",
    "Bloqueo AV 2:1",
    "BAV 2:1",
    "Conducción AV",
    { av: "two_one", hr: 80, pr: 180, variability: 0 },
    "Una de cada dos activaciones auriculares alcanza el ventrículo.",
    ["Dos P por cada QRS", "No permite clasificar Mobitz I/II por sí solo"],
  ),
  p(
    "highav",
    "Bloqueo AV de alto grado",
    "BAV alto grado",
    "Conducción AV",
    { av: "high", hr: 90, pr: 180, variability: 0 },
    "Dos P consecutivas no conducidas entre latidos conducidos.",
    ["Conducción 3:1 en este caso", "Bradicardia ventricular"],
  ),
  p(
    "complete",
    "BAV completo · escape de la unión",
    "BAV completo",
    "Conducción AV",
    {
      av: "complete",
      hr: 45,
      atrialRate: 85,
      escape: "junctional",
      variability: 0,
    },
    "Relojes auricular y ventricular independientes.",
    [
      "P regulares más rápidas que QRS",
      "Sin relación PR fija",
      "Escape estrecho",
    ],
  ),
  p(
    "complete_v",
    "BAV completo · escape ventricular",
    "Escape ventricular",
    "Conducción AV",
    {
      av: "complete",
      hr: 30,
      atrialRate: 80,
      escape: "ventricular",
      qrs: 165,
      axis: -65,
      variability: 0,
    },
    "Disociación AV con escape de origen ventricular.",
    ["Actividad auricular independiente", "QRS ancho a 30 lpm"],
  ),
  p(
    "rbbb",
    "Bloqueo completo de rama derecha",
    "BRD",
    "Conducción intraventricular",
    { conduction: "rbbb", qrs: 150, axis: 35 },
    "Activación tardía del ventrículo derecho.",
    [
      "rSR′ en V1",
      "S terminal ancha lateral",
      "QRS ≥120 ms; T negativa derecha",
    ],
  ),
  p(
    "irbbb",
    "Bloqueo incompleto de rama derecha",
    "BRD incompleto",
    "Conducción intraventricular",
    { conduction: "irbbb", qrs: 115, axis: 35 },
    "Retraso moderado de la activación ventricular derecha.",
    ["Morfología de BRD", "QRS configurado 115 ms (adulto)"],
  ),
  p(
    "lbbb",
    "Bloqueo completo de rama izquierda",
    "BRI",
    "Conducción intraventricular",
    { conduction: "lbbb", qrs: 160, axis: -15, septalQ: false },
    "Activación ventricular izquierda retrasada y secuencia septal modificada.",
    [
      "QS/rS en V1",
      "R lateral ancha con muesca",
      "Repolarización secundaria discordante",
    ],
  ),
  p(
    "lafb",
    "Hemibloqueo anterior izquierdo",
    "HBAI",
    "Conducción intraventricular",
    { conduction: "lafb", qrs: 100, axis: -60 },
    "Rotación de la activación frontal hacia superior e izquierda.",
    ["Eje −45° a −90°", "Predominio positivo I/aVL, negativo inferior"],
    "vectorial",
    "Reproduce eje; detalle qR/rS de todos los fascículos es aproximado.",
  ),
  p(
    "lpfb",
    "Hemibloqueo posterior izquierdo",
    "HBPI",
    "Conducción intraventricular",
    { conduction: "lpfb", qrs: 100, axis: 120 },
    "Rotación de la activación frontal hacia inferior y derecha.",
    ["Desviación derecha del eje", "Excluir otras causas de eje derecho"],
    "vectorial",
    "Reproduce eje; no demuestra criterios clínicos excluyentes de HBPI.",
  ),
  p(
    "bifascicular",
    "BRD + hemibloqueo anterior izquierdo",
    "Bifascicular",
    "Conducción intraventricular",
    { conduction: "rbbb_lafb", qrs: 150, axis: -60 },
    "Retraso de rama derecha y desviación izquierda de la activación.",
    ["Morfología BRD", "Eje izquierdo marcado"],
  ),
  p(
    "bifascicular_pr",
    "Bifascicular + BAV de primer grado",
    "Bifascicular + PR",
    "Conducción intraventricular",
    { conduction: "rbbb_lafb", av: "first", qrs: 150, axis: -60, pr: 260 },
    "BRD, eje izquierdo y PR prolongado coexistentes.",
    [
      "BRD + HBAI",
      "PR prolongado",
      "El PR no localiza el retraso al fascículo restante",
    ],
  ),
  p(
    "wpw",
    "Preexcitación ventricular",
    "WPW",
    "Conducción intraventricular",
    { conduction: "wpw", pr: 100, qrs: 135 },
    "Adición de una activación ventricular inicial lenta.",
    ["PR corto", "Ascenso inicial empastado", "QRS ancho"],
    "vectorial",
    "Delta aproximada; sin vías accesorias anatómicas ni circuito AVRT.",
  ),
  p(
    "inferior",
    "Lesión inferior · predominio en III",
    "Inferior (CD)",
    "Isquemia y ST",
    { ischemia: "inferior_rca", st: 2 },
    "Vector de lesión orientado hacia inferior y derecha.",
    [
      "ST↑ II, III y aVF, III >II",
      "ST↓ recíproco en I y aVL",
      "La arteria no se determina solo por ECG",
    ],
  ),
  p(
    "inferior_lcx",
    "Lesión inferior · predominio en II",
    "Inferior (Cx)",
    "Isquemia y ST",
    { ischemia: "inferior_lcx", st: 2 },
    "Vector de lesión inferior con mayor componente izquierdo.",
    ["ST↑ II ≥III", "I isoeléctrica o elevada"],
  ),
  p(
    "anterior",
    "Lesión anterior",
    "Anterior",
    "Isquemia y ST",
    { ischemia: "anterior", st: 2 },
    "Vector de lesión dirigido hacia la pared anterior.",
    [
      "Elevación ST precordial anterior",
      "Repolarización dependiente de la fase",
    ],
  ),
  p(
    "lateral",
    "Lesión lateral",
    "Lateral",
    "Isquemia y ST",
    { ischemia: "lateral", st: 2 },
    "Vector de lesión dirigido a la pared lateral.",
    ["ST↑ I, aVL y V5–V6", "Descenso inferior recíproco"],
  ),
  p(
    "posterior",
    "Patrón de lesión posterior",
    "Posterior",
    "Isquemia y ST",
    { ischemia: "posterior", st: 2 },
    "Representación especular anterior de una lesión posterior.",
    ["ST↓ V1–V3", "Aumento de R anterior"],
    "local",
    "Corrección local de R; V7–V9 pendientes.",
  ),
  p(
    "rv_infarct",
    "Lesión ventricular derecha",
    "Ventrículo derecho",
    "Isquemia y ST",
    { ischemia: "rv", st: 2 },
    "Vector de lesión inferior y anterior derecho.",
    [
      "Elevación ST en V1 e inferiores",
      "Completar con derivaciones derechas en la práctica",
    ],
    "vectorial",
    "V3R–V4R pendientes; no reproduce todos los criterios territoriales.",
  ),
  p(
    "diffuse",
    "ST descendido difuso + aVR elevado",
    "ST difuso / aVR",
    "Isquemia y ST",
    { ischemia: "diffuse", st: 2 },
    "Vector de lesión subendocárdica global.",
    [
      "ST↓ en múltiples derivaciones",
      "ST↑ en aVR",
      "Patrón inespecífico de arteria y de infarto",
    ],
  ),
  p(
    "subendo",
    "Patrón de isquemia subendocárdica",
    "Isquemia subendocárdica",
    "Isquemia y ST",
    { ischemia: "subendo", st: 2, tAxis: -140 },
    "Alteración subendocárdica de repolarización.",
    [
      "Descenso ST",
      "Puede asociar T negativa",
      "El diagnóstico de IAM requiere contexto y troponina",
    ],
  ),
  p(
    "wellens_a",
    "Patrón de Wellens · tipo A",
    "Wellens A",
    "Isquemia y ST",
    { ischemia: "wellens_a" },
    "Alteración regional de la onda T en precordiales anteriores.",
    ["T bifásica V2–V3", "ST casi isoeléctrico"],
    "local",
  ),
  p(
    "wellens_b",
    "Patrón de Wellens · tipo B",
    "Wellens B",
    "Isquemia y ST",
    { ischemia: "wellens_b" },
    "Inversión profunda y simétrica de T anterior.",
    ["T negativa V2–V3", "Interpretación dependiente del contexto clínico"],
    "local",
  ),
  p(
    "de_winter",
    "Patrón de de Winter",
    "De Winter",
    "Isquemia y ST",
    { ischemia: "de_winter" },
    "Representación de ST ascendente deprimido y T anterior prominente.",
    ["ST↓ ascendente precordial", "T altas y simétricas"],
    "local",
    "No garantiza ST↑ en aVR; patrón parcial señalado como aproximado.",
  ),
  p(
    "sgarbossa",
    "BRI con lesión concordante",
    "Sgarbossa",
    "Isquemia y ST",
    {
      conduction: "lbbb",
      qrs: 160,
      axis: -15,
      ischemia: "sgarbossa",
      st: 3,
      septalQ: false,
    },
    "Se añade lesión al BRI para explorar concordancia del ST.",
    ["QRS ancho tipo BRI", "ST positivo lateral concordante"],
    "vectorial",
    "Caso ilustrativo; sin cálculo automático de score ni ajuste de criterio proporcional.",
  ),
  p(
    "pericarditis",
    "Patrón de pericarditis",
    "Pericarditis",
    "Isquemia y ST",
    { ischemia: "pericarditis", st: 1.5, stShape: "concave" },
    "Elevación extendida del ST y desviación opuesta del PR.",
    ["ST↑ cóncavo difuso", "PR↓ y PR↑ en aVR"],
    "local",
    "Dipolo único no garantiza elevación en todas las derivaciones; no diagnostica pericarditis.",
  ),
  p(
    "rv_acute",
    "Sobrecarga aguda del ventrículo derecho",
    "Sobrecarga VD aguda",
    "Sobrecarga",
    {
      overload: "rv_acute",
      hr: 110,
      axis: 110,
      conduction: "irbbb",
      qrs: 115,
      pAmp: 0.28,
    },
    "Activación y repolarización orientadas hacia ventrículo derecho.",
    ["Taquicardia y eje derecho", "BRD incompleto y T negativa derecha"],
    "vectorial",
    "No reproduce S1Q3T3 de forma consistente; ECG no confirma ni excluye TEP.",
  ),
  p(
    "rv_chronic",
    "Hipertrofia del ventrículo derecho",
    "Hipertrofia VD",
    "Sobrecarga",
    { overload: "rv_chronic", axis: 115, pAmp: 0.3, qrsAmp: 1.2 },
    "Aumento de fuerzas anteriores derechas.",
    ["R dominante V1", "Eje derecho", "Alteración secundaria ST–T"],
    "vectorial",
    "Criterios de voltaje individuales no validados; no modela anatomía real.",
  ),
  p(
    "lvh",
    "Hipertrofia del ventrículo izquierdo",
    "Hipertrofia VI",
    "Sobrecarga",
    { overload: "lv", axis: 0, qrsAmp: 1.5, tAxis: 160 },
    "Aumento de fuerzas del ventrículo izquierdo.",
    ["Voltaje precordial aumentado", "Sobrecarga lateral"],
    "vectorial",
    "Los criterios Sokolow-Lyon/Cornell no se calculan automáticamente.",
  ),
  p(
    "aai",
    "Estimulación auricular AAI",
    "AAI",
    "Marcapasos",
    { rhythm: "paced", pacing: "AAI", hr: 60 },
    "Estímulos auriculares periódicos con conducción AV.",
    ["Espiga antes de P", "QRS intrínseco estrecho"],
    "vectorial",
    "Estimulación capturada a frecuencia fija; sensado, demanda y fallos pendientes.",
  ),
  p(
    "vvi",
    "Estimulación ventricular VVI",
    "VVI",
    "Marcapasos",
    { rhythm: "paced", pacing: "VVI", hr: 60, qrs: 165, axis: -65 },
    "Estimulación ventricular representativa desde VD.",
    ["Espiga antes de QRS", "QRS ancho tipo BRI y eje superior"],
    "vectorial",
    "Estimulación capturada a frecuencia fija; sensado, demanda y fallos pendientes.",
  ),
  p(
    "ddd",
    "Estimulación secuencial DDD",
    "DDD",
    "Marcapasos",
    { rhythm: "paced", pacing: "DDD", hr: 65, qrs: 160, axis: -65, pr: 180 },
    "Estímulos auricular y ventricular separados por intervalo AV.",
    ["Dos espigas por ciclo", "P seguida de QRS estimulado"],
    "vectorial",
    "Secuencia fija; no simula demanda, PVARP, seguimiento ni límite superior.",
  ),
  p(
    "hyperk",
    "Hiperpotasemia · T prominente",
    "Hiperpotasemia",
    "Otros patrones",
    { electrolyte: "hyperkalemia", qrs: 110, pAmp: 0.07 },
    "Aproximación morfológica de T picuda y reducción de P.",
    ["T altas y estrechas", "Disminución de P"],
    "vectorial",
    "Sin relación concentración–ECG, ni evolución a onda sinusoidal.",
  ),
  p(
    "hypok",
    "Hipopotasemia · onda U",
    "Hipopotasemia",
    "Otros patrones",
    { electrolyte: "hypokalemia", hr: 60 },
    "Reducción de T y aparición de U prominente.",
    ["T aplanada", "U prominente"],
    "vectorial",
    "El delineador puede confundir T y U; QT automático no fiable.",
  ),
  p(
    "longqt",
    "QT prolongado",
    "QT largo",
    "Otros patrones",
    { qtc: 540, hr: 60, electrolyte: "longqt" },
    "Prolongación de la repolarización ventricular.",
    ["QTc configurado 540 ms", "QT se adapta mediante Fridericia"],
  ),
  p(
    "shortqt",
    "QT corto",
    "QT corto",
    "Otros patrones",
    { qtc: 290, hr: 60, electrolyte: "shortqt" },
    "Acortamiento de la repolarización ventricular.",
    ["QTc configurado 290 ms"],
  ),
  p(
    "lowvoltage",
    "Bajo voltaje",
    "Bajo voltaje",
    "Otros patrones",
    { electrolyte: "lowvoltage", qrsAmp: 0.7, pAmp: 0.08, tAmp: 0.15 },
    "Disminución de amplitudes sin alterar la secuencia de activación.",
    ["Complejos de baja amplitud"],
    "vectorial",
    "La etiología y la alternancia eléctrica no están modeladas.",
  ),
  ...[
    "Brugada tipo 1",
    "Hipotermia · onda de Osborn",
    "Efecto digitálico",
    "Alternancia eléctrica",
    "Dextrocardia",
  ].map((name, i) =>
    p(
      "pending_" + i,
      name,
      name,
      "Pendientes",
      {},
      "",
      [],
      "pending",
      "Requiere modelo morfológico específico y criterios de aceptación adicionales.",
    ),
  ),
];
export function fromPreset(preset: Preset, view?: ECGCase["view"]): ECGCase {
  const c = cloneCase(DEFAULT_CASE);
  Object.assign(c, preset.patch);
  c.presetId = preset.id;
  c.name = preset.name;
  if (view) c.view = { ...view };
  return c;
}
export const presetById = (id: string) => PRESETS.find((p) => p.id === id);
